server:
  port: 8080

spring:
  config:
    activate:
      on-profile: oauth

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/happyjar
    username: happyjar
    password: mamasclub

#    url: jdbc:postgresql://51.13.127.233:5432/happyjar
#    username: happyjar
#    password: mamasclub@1

  jpa:
    hibernate:
      format-sql: true
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  data

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
